name: Node.js CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install requirements
      run: yarn install
    - name: run linter
      run: yarn run eslint .
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install requirements
      run: yarn install
    - name: build docker
      run: docker-compose build
    - name: run jest initial crawl
      run: sudo yarn jest
    - name: run jest
      run: sudo yarn jest
        




